source "https://rubygems.org"

gem "jekyll", "~> 4.1"
gem "jekyll-sitemap", "~> 1.4.0"
gem "jekyll-mentions", "~> 1.6.0"
gem "jekyll-paginate", "~> 1.1.0"
gem "jekyll-seo-tag", "~> 2.6.1"
gem "jekyll-redirect-from", "~> 0.16"
gem "jekyll-feed", "~> 0.15"
gem "jekyll-commonmark", "~> 1.3.1"
gem "jekyll-include-cache", "~> 0.2"
gem "jemoji", "~> 0.12"
gem "jekyll-remote-theme", "~> 0.3"
gem "activesupport", "7.0.5.1"
gem "public_suffix", "5.0.1"
gem "gemoji", "4.1.0"
gem "google-protobuf", "3.23.3"
gem "sass-embedded", "1.63.6"
gem "jekyll-sass-converter", "3.0.0"
gem "kramdown", "2.4.0"
gem "mercenary", "0.4.0"
gem "rouge", "4.1.2"
gem "unicode-display_width", "2.4.2"
gem "terminal-table", "3.0.2"
gem "webrick", "1.8.1"
